Tweaked version that includes live Query and Editing Pages using a live Virtuoso Instance.
athalhammer/meta-way pull request #1
Opened 2021-10-27 16:43 UTC by kidehen

A few tweaks using a live Virtuoso instance (i.e., what's at https://linkeddata.uriburner.com/sparql) that adds the following:

1. Use of Relative URIs rather e.g., negating the need for example.com
2. Live Query Results comprising Links that demonstrate Linked Data connectivity effects via follow-your-nose exploration

2021-11-01 20:35 UTC, athalhammer requested changes
Thanks @kidehen! I added some suggestions. All of them make the examples coherent so they rely on the original repository. This is important, in particular, if I introduce changes later they will be reflected also in all of the examples.

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +PREFIX : <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl#>
```suggestion
PREFIX : <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl#>
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +FROM <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl>
```suggestion
FROM <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/krr.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/krr.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/aii.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/aii.ttl>
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +* [Live Query Results Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2F
```suggestion
* [Live Query Results Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%23%3E%0D%0A%0D%0ASELECT+%3Fprod+%3FupperClass+%28COUNT%28%3FupperClass%29+AS+%3Fcount%29++%0D%0AFROM+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Fkrr.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Faii.ttl%3E%0D%0A%0D%0AWHERE+%7B%0D%0A++++++++%3Fs+rdfs%3AsubClassOf%2B+%3FupperClass+.%0D%0A++++++++%3Fs+rdfs%3AisDefinedBy+%3Fprod.%0D%0A++++++++VALUES+%3FupperClass+%7B%3AUnit+%3AFood%7D+%0D%0A%7D+%0D%0AGROUP+BY+%3Fprod+%3FupperClass&should-sponge=&format=text%2Fx-html%2Btr&timeout=30000000)
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +* [Live Query Editor Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&qtxt=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2Fra
```suggestion
* [Live Query Editor Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&qtxt=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%23%3E%0D%0A%0D%0ASELECT+%3Fprod+%3FupperClass+%28COUNT%28%3FupperClass%29+AS+%3Fcount%29++%0D%0AFROM+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Fkrr.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Faii.ttl%3E%0D%0A%0D%0AWHERE+%7B%0D%0A++++++++%3Fs+rdfs%3AsubClassOf%2B+%3FupperClass+.%0D%0A++++++++%3Fs+rdfs%3AisDefinedBy+%3Fprod.%0D%0A++++++++VALUES+%3FupperClass+%7B%3AUnit+%3AFood%7D+%0D%0A%7D+%0D%0AGROUP+BY+%3Fprod+%3FupperClass&should-sponge=&format=text%2Fx-html%2Btr&timeout=30000000)
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +PREFIX : <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl#>
```suggestion
PREFIX : <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl#>
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +FROM <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl>
```suggestion
FROM <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/krr.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/krr.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/aii.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/aii.ttl>
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +* [Live Query Results Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+rdf%3A+%3Chttp%3A%2F%
```suggestion
* [Live Query Results Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+krr%3A+%3Chttps%3A%2F%2Fkrr.example.com%2F%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%23%3E%0D%0A%0D%0ASELECT+DISTINCT+*+%0D%0AFROM+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Fkrr.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Faii.ttl%3E%0D%0AWHERE+%7B%0D%0A++++++++%3Fs+krr%3Ayee3zei8+krr%3Aootafai8i+.%0D%0A++++++++%3Fs+%3Fp+%3Fo++.%0D%0A++++++++OPTIONAL+%7B%3Fp+rdfs%3Alabel+%3FpredicateLabel.%7D%0D%0A++++++++OPTIONAL+%7B%3Fo+rdfs%3Alabel+%3FobjectLabel%7D%0D%0A+++++%7D&should-sponge=&format=text%2Fx-html%2Btr&timeout=30000000)
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +* [Live Query Editor Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&qtxt=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+rdf%3A+%3Chttp%3A%2F%2F
```suggestion
* [Live Query Editor Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&qtxt=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+krr%3A+%3Chttps%3A%2F%2Fkrr.example.com%2F%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%23%3E%0D%0A%0D%0ASELECT+DISTINCT+*+%0D%0AFROM+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Fkrr.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Faii.ttl%3E%0D%0AWHERE+%7B%0D%0A++++++++%3Fs+krr%3Ayee3zei8+krr%3Aootafai8i+.%0D%0A++++++++%3Fs+%3Fp+%3Fo++.%0D%0A++++++++OPTIONAL+%7B%3Fp+rdfs%3Alabel+%3FpredicateLabel.%7D%0D%0A++++++++OPTIONAL+%7B%3Fo+rdfs%3Alabel+%3FobjectLabel%7D%0D%0A+++++%7D&should-sponge=&format=text%2Fx-html%2Btr&timeout=30000000)

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +PREFIX : <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl#>
```suggestion
PREFIX : <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl#>
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +FROM <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl>
```suggestion
FROM <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/krr.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/krr.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/aii.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/aii.ttl>
```

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +* [Live Query Results Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2F
```suggestion
* [Live Query Results Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&query=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%23%3E%0D%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0Aprefix+aii%3A+%3Chttps%3A%2F%2Faii.example.com%2F%3E%0D%0A%0D%0ASELECT+DISTINCT+*+%0D%0AFROM+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Fkrr.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Faii.ttl%3E%0D%0AWHERE+%7B%0D%0A++++++++%3Fs+aii%3Aahch9aix+aii%3Apah7chae+.%0D%0A++++++++%3Fs+%3Fp+%3Fo++.%0D%0A++++++++OPTIONAL+%7B%3Fp+rdfs%3Alabel+%3FpredicateLabel.%7D%0D%0A++++++++OPTIONAL+%7B%3Fo+rdfs%3Alabel+%3FobjectLabel%7D%0D%0A%7D+&should-sponge=&format=text%2Fx-html%2Btr&timeout=30000000)

2021-11-01 20:35 UTC, athalhammer commented on README.md
> +* [Live Query Editor Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&qtxt=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2Fra
```suggestion
* [Live Query Editor Page](http://linkeddata.uriburner.com/sparql/?default-graph-uri=&qtxt=PREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+%3A+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%23%3E%0D%0APREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0Aprefix+aii%3A+%3Chttps%3A%2F%2Faii.example.com%2F%3E%0D%0A%0D%0ASELECT+DISTINCT+*+%0D%0AFROM+%3Chttps%3A%2F%2Fraw.githubusercontent.com%2Fathalhammer%2Fmeta-way%2Fmain%2Fdata%2Fupper-ontology.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Fkrr.ttl%3E+%0D%0AFROM+%3Chttps%3A%2F%2Fgithub.com%2Fathalhammer%2Fmeta-way%2Fblob%2Fmain%2Fdata%2Faii.ttl%3E%0D%0AWHERE+%7B%0D%0A++++++++%3Fs+aii%3Aahch9aix+aii%3Apah7chae+.%0D%0A++++++++%3Fs+%3Fp+%3Fo++.%0D%0A++++++++OPTIONAL+%7B%3Fp+rdfs%3Alabel+%3FpredicateLabel.%7D%0D%0A++++++++OPTIONAL+%7B%3Fo+rdfs%3Alabel+%3FobjectLabel%7D%0D%0A%7D+&should-sponge=&format=text%2Fx-html%2Btr&timeout=30000000)
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +SPARQL CLEAR GRAPH <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl> ;
```suggestion
SPARQL CLEAR GRAPH <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl> ;
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +SPARQL CLEAR GRAPH <https://github.com/kidehen/meta-way/blob/main/data/krr.ttl> ;
```suggestion
SPARQL CLEAR GRAPH <https://github.com/athalhammer/meta-way/blob/main/data/krr.ttl> ;
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +SPARQL CLEAR GRAPH <https://github.com/kidehen/meta-way/blob/main/data/aii.ttl> ;
```suggestion
SPARQL CLEAR GRAPH <https://github.com/athalhammer/meta-way/blob/main/data/aii.ttl> ;
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +PREFIX : <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl#>
```suggestion
PREFIX : <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl#>
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +                GRAPH <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl>
```suggestion
                GRAPH <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +PREFIX : <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl#>
```suggestion
PREFIX : <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl#>
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +                GRAPH <https://github.com/kidehen/meta-way/blob/main/data/krr.ttl> {
```suggestion
                GRAPH <https://github.com/athalhammer/meta-way/blob/main/data/krr.ttl> {
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +                PREFIX : <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl#>
```suggestion
                PREFIX : <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl#>
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +                GRAPH <https://github.com/kidehen/meta-way/blob/main/data/aii.ttl> {
```suggestion
                GRAPH <https://github.com/athalhammer/meta-way/blob/main/data/aii.ttl> {
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +PREFIX : <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl#>
```suggestion
PREFIX : <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl#>
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +FROM <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl>
```suggestion
FROM <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/krr.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/krr.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/aii.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/aii.ttl>
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +PREFIX : <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl#>
```suggestion
PREFIX : <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl#>
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +FROM <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl>
```suggestion
FROM <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/krr.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/krr.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/aii.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/aii.ttl>
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +PREFIX : <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl#>
```suggestion
PREFIX : <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl#>
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +FROM <https://raw.githubusercontent.com/kidehen/meta-way/main/data/upper-ontology.ttl>
```suggestion
FROM <https://raw.githubusercontent.com/athalhammer/meta-way/main/data/upper-ontology.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/krr.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/krr.ttl> 
```

2021-11-01 20:35 UTC, athalhammer commented on scripts/sql/upper-ontology-demo1.sql
> +FROM <https://github.com/kidehen/meta-way/blob/main/data/aii.ttl>
```suggestion
FROM <https://github.com/athalhammer/meta-way/blob/main/data/aii.ttl>
```

2021-11-01 21:38 UTC, kidehen commented
> Thanks @kidehen! I added some suggestions. All of them make the examples coherent so they rely on the original repository. This is important, in particular, if I introduce changes later they will be reflected also in all of the examples.

My changes re FROM CLAUSE and URI prefixes are very specific to the needs of the live instance we host at: http://linkeddata.uriburner.com/sparql . 

You don't really need to add these changes, I just wanted to demonstrate how they this could be available in live form showcasing linked data principles :)

2021-11-02 17:47 UTC, athalhammer commented
Nice, thanks @kidehen! So I close it without merging according to your suggestion

2021-11-02 17:47 UTC, closed without merging